language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "radixdlt-github"
    token:
      secure: "sKRyzyJjCjfRHDaIBcIULKqVEvdUGRXOAgv3O+H8cE2xCaW6+Ea9eVWhZtpkpjvdXs4agJ+3VSQse+1974Zf3eMK6Cal/RpT+XvuNo8rgB633EcHw27p8BRw51fTXiLWavlYymo+Mw6WByyIClqAP8+5kuB0Oe/0JIVla/a/s4NX7hdTOj3wnh/btoYyUit4x9e+K8bqbqQPj3b4fLdk8LSMjEHP9sfxdr6zuP52YigZ17dW/SsSiAN89fVqfkuqOZ4QYj98HZh2r7OwPCqCP4eg4GTBvrv+yGq3MQQr57tv8LfRJWn7eQNY9bnWnq9YTXDA7yMtyV6iahSgyQWVLRcpePwnfk+gPowOyuAz2FKytU2/KXzFl7kVKQn4vuE6MMsVpjy1kkU+ZUlJxmPcKz4FIY34UG683AbX8RQiHul0PjdG4twopMdOdr4yZik/rh0c6ZBQVdgWKsiVqXvBWDn4XP1w3NOkDHaraVu+9Q7XTVqfax1j/xZodKlL8jkyytT5vdPT6BqJUH4UJwWgWJLLfZfXMiQSLM8RZde89hkfq0byoR8AlVoUVoQGDPDrjgqnBN/8iJAVEfaXg+/0LKnSV9+7LLvbUNR9HE+hI2cqQKe1+3t6fowBGh3TKFSS/0RuKDdfd4K+iF1Wo6WOZN1mrPrqXvZ14azbvOvQEpM="

jdk:
  - openjdk8

jobs:
  include:
    - stage: check
      script: ./gradlew check
    - stage: test
      script: ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
