language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "radixdlt-github"
    token:
      secure: "nesc1noLFiLk7XNEF9Ku8ynCJS2ze3jSyjpy8rwb9GksUoutlAAX3ZnvjdEGM9lIrIqRbW+hyEzDNI27pcWiMr2wi76J0ng65wu1wWscwToV1DtY574/T36U46taCheorGByOK7RPmyxkBi01rSYucJwdOClQ5VChExkQuJ9jSYQPwjhVumUBJbQ5KpDiHVyqdtFIafGyVjxPuaxNGQsNT6y72l+IGWj7EsrOpK6JL3Y0NntafJenzyXIUPyZT9SstHznHx7zDSF8Ci2N9w0e/FttCRVsSWKUg/pVCRu2C8mInzHmSxT1NJuT3MuSPRkU7ahiGfJP/srnxFrwb4uL3tlkUwlvR3KIUv6IFMTvuo17yy1QZa8ns8cDwanmKW+J3ZZq7ojJ1Ijyk4MCNdVkR8cEI8wduZSOo0zUwjgjZPdUNL8v7mFk5vScJzS187EeidCdSCZS2zIjmHru/sulJ5WeKSz7oqckSOGx4pZiN00Sq1YB9Qd0NSJOxE9v9bswuMjF4YpwZqH/SPjS+imt92kTOshqnaZsP0XtH41WYMX+mxp1YDVfMUeHaS9L14lY4u46mNgY/xQOTJL6sWOMO+cnHXFvfge2pYLGEymezCGC5qoxmA2eVzECc6f1tgB3/K1KoBORZ8VsYKwSm/bU9Ig1+VUUZi26PIngakUgE4="

jdk:
  - openjdk8

jobs:
  include:
    - stage: check
      script: ./gradlew check
    - stage: test
      script: ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
